---
- name: Ansible to setup the machine
  hosts: all 
  sudo: True
  tasks:
  - name: apt-get some stuff
    apt: name={{item}} state=installed
    with_items:
       - htop
       - multitail
       - python-usb
       - python-setuptools
       - openssh-server

  - git: repo=https://github.com/xypron/pyrelayctl
       dest=/opt/pyrelayctl


