---
- name: Ansible to setup the machine
  hosts: all 
  sudo: True
  tasks:
  - name: apt-get some stuff
    apt: name={{item}} state=installed
    with_items:
       - htop
       - multitail
       - python-usb
       - python-setuptools
       - openssh-server
       - python3-usb
       - python3-pip

  - git: repo=https://github.com/jgumbley/braubuddy
       dest=/opt/braubuddy


