---
- name: This is a hello-world example
  hosts: all 
  sudo: True
  tasks:
  - name: hello
    apt: name={{item}} state=installed
    with_items:
       - python-usb
       - python-setuptools

  - git: repo=https://github.com/padelt/temper-python
       dest=/opt/temper-python

  - command: python setup.py install
    args:
        chdir: /opt/temper-python
        creates: /usr/local/bin/temper-poll

