---
- name: Ansible to setup the machine
  hosts: all 
  sudo: True
  tasks:
  - name: apt-get some stuff
    apt: name={{item}} state=installed
    with_items:
       - python-usb
       - python-setuptools
       - openssh-server

  - git: repo=https://github.com/padelt/temper-python
       dest=/opt/temper-python

  - command: python setup.py install
    args:
        chdir: /opt/temper-python
        creates: /usr/local/bin/temper-poll

